title: Endowing Micro-swimmers with Artificial Intelligence
description: Online Workshop

# Build settings
markdown: kramdown
# theme: minima
theme: jekyll-theme-slate
# remote_theme: poole/lanyon
# theme: jekyll-swiss
theme_color: white
plugins:
  - jekyll-feed
