title: UMM CSci 1301, Fall 2019
email: mcphee@morris.umn.edu
description: >- # this means to ignore newlines until "baseurl:"
  Problem sets, labs, and other materials for the Fall, 2019, edition of
  CSci 1301 at the University of Minnesota Morris.
baseurl: "/csci-1301-fall-2019" # the subpath of your site, e.g. /blog
url: "http://https://umm-csci.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: NicMcPhee
github_username:  NicMcPhee

# Build settings
markdown: kramdown
theme: minima
# theme: jekyll-theme-slate
# theme: jekyll-swiss
theme_color: white
plugins:
  - jekyll-feed
