title: 
#  description: >- # this means to ignore newlines until "baseurl:"
#  Problem sets, labs, and other materials for the Fall, 2019, edition of
#  CSci 1301 at the University of Minnesota Morris.

# Build settings
markdown: kramdown
# theme: minima
theme: jekyll-theme-slate
# theme: jekyll-swiss
theme_color: white
plugins:
  - jekyll-feed
