title: Endowing Micro-swimmers with Artificial Intelligence
description: Welcome to the Online Workshop

# Build settings
markdown: kramdown
# theme: minima
theme: jekyll-theme-tactile
# theme: jekyll-swiss
theme_color: white
plugins:
  - jekyll-feed
