title: Endowing Micro-swimmers with Artificial Intelligence
description: >- # this means to ignore newlines until "baseurl:"
#  Welcome to the Online Worshop

# Build settings
markdown: kramdown
# theme: minima
theme: jekyll-theme-slate
# theme: jekyll-swiss
theme_color: white
plugins:
  - jekyll-feed
